service: self-hosted-runner
runtime: custom
env: flex

resources:
    cpu: 4
    memory_gb: 16
    disk_size_gb: 128

automatic_scaling:
    min_num_instances: 4
    max_num_instances: 20
    cpu_utilization:
        target_utilization: 0.8
    target_concurrent_requests: 5
